workspace = { members = ["rust-lua-bind"] }
[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
bevy_mod_scripting = { version = "0.3.0", path = "../bevy_mod_scripting", features = ["lua54", "lua_script_api"] }
bevy_script_api = { version = "0.3.0", path = "../bevy_mod_scripting/bevy_script_api" }
